#!/usr/bin/env bash
# Conservative 24GB single-GPU smoke for Qwen2.5-1.5B GRPO on GSM8K.
# Use this before the full 1.5B baseline on RTX 4090 / 3090 / A10-class cards.
set -euo pipefail

export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-8}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-4}
export PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}
export ROLLOUT_N=${ROLLOUT_N:-2}
export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-512}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-256}
export PPO_MAX_TOKEN_LEN_PER_GPU=${PPO_MAX_TOKEN_LEN_PER_GPU:-2048}
export LOG_PROB_MAX_TOKEN_LEN_PER_GPU=${LOG_PROB_MAX_TOKEN_LEN_PER_GPU:-2048}
export ROLLOUT_GPU_MEM_UTIL=${ROLLOUT_GPU_MEM_UTIL:-0.40}
export ROLLOUT_MAX_MODEL_LEN=${ROLLOUT_MAX_MODEL_LEN:-768}
export ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-1024}
export ROLLOUT_MAX_NUM_SEQS=${ROLLOUT_MAX_NUM_SEQS:-16}
export TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-20}
export SAVE_FREQ=${SAVE_FREQ:--1}
export TEST_FREQ=${TEST_FREQ:-10}
export LOG_VAL_GENERATIONS=${LOG_VAL_GENERATIONS:-4}
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-qwen25_1p5b_gsm8k_grpo_24g_safe}

exec /workspace/scripts_grpo/04_cloud_grpo_qwen25_1p5b_gsm8k.sh "$@"