"""HIVE selector infrastructure."""

from signal_forge.hive.identity import PromptIdentityError, attach_stable_prompt_ids, extract_stable_prompt_ids
from signal_forge.hive.prompt_entropy import (
    PromptEntropyBatchResult,
    PromptEntropyDiagnostics,
    PromptEntropyEvaluator,
    PromptEntropyInputBatch,
    PromptEntropyRecord,
    full_categorical_entropy,
)
from signal_forge.hive.stage1 import (
    ExplorationControllerConfig,
    ExplorationUpdate,
    RewardHistorySignal,
    Stage1BatchResult,
    Stage1Config,
    Stage1Diagnostics,
    Stage1PromptDecision,
    Stage1StepSelector,
    apply_exploration_update,
    compute_exploration_update,
    compute_reward_history_signal,
)
from signal_forge.hive.state import (
    HIVE_STATE_FILENAME,
    HiveSelectorSnapshot,
    HiveSelectorState,
    PromptHistory,
    PromptVisit,
    RewardGroupClassification,
    ZeroVarianceType,
    classify_zero_variance,
    restore_selector_rng,
)

__all__ = [
    "ExplorationControllerConfig",
    "ExplorationUpdate",
    "HIVE_STATE_FILENAME",
    "HiveSelectorSnapshot",
    "HiveSelectorState",
    "PromptHistory",
    "PromptIdentityError",
    "PromptEntropyBatchResult",
    "PromptEntropyDiagnostics",
    "PromptEntropyEvaluator",
    "PromptEntropyInputBatch",
    "PromptEntropyRecord",
    "PromptVisit",
    "RewardGroupClassification",
    "RewardHistorySignal",
    "Stage1BatchResult",
    "Stage1Config",
    "Stage1Diagnostics",
    "Stage1PromptDecision",
    "Stage1StepSelector",
    "ZeroVarianceType",
    "apply_exploration_update",
    "attach_stable_prompt_ids",
    "classify_zero_variance",
    "compute_exploration_update",
    "compute_reward_history_signal",
    "extract_stable_prompt_ids",
    "full_categorical_entropy",
    "restore_selector_rng",
]
