"""HIVE selector infrastructure."""

from signal_forge.hive.actor_rpc import ActorEntropyCallDiagnostics, compute_prompt_entropy_rpc
from signal_forge.hive.identity import PromptIdentityError, attach_stable_prompt_ids, extract_stable_prompt_ids
from signal_forge.hive.prompt_preprocessing import (
    CanonicalHivePrompt,
    HivePromptPreprocessor,
    validate_hive_prompt_preprocessing_scope,
)
from signal_forge.hive.prompt_entropy import (
    PromptEntropyBatchResult,
    PromptEntropyDiagnostics,
    PromptEntropyEvaluator,
    PromptEntropyInputBatch,
    PromptEntropyRecord,
    full_categorical_entropy,
)
from signal_forge.hive.pre_rollout import (
    HivePreRolloutConfig,
    HivePreRolloutPreparedRound,
    HivePreRolloutRoundResult,
    HivePreRolloutStep,
    HivePreRolloutStepResult,
)
from signal_forge.hive.stage1 import (
    ExplorationControllerConfig,
    ExplorationUpdate,
    RewardHistorySignal,
    Stage1BatchResult,
    Stage1Config,
    Stage1Diagnostics,
    Stage1PromptDecision,
    Stage1StepSelector,
    apply_exploration_update,
    compute_exploration_update,
    compute_reward_history_signal,
)
from signal_forge.hive.stage2 import (
    EntropyScoredPrompt,
    Stage2BatchResult,
    Stage2Config,
    Stage2Diagnostics,
    Stage2PromptRecord,
    Stage2Selector,
    compute_stage2_counts,
)
from signal_forge.hive.state import (
    HIVE_STATE_FILENAME,
    HiveSelectorSnapshot,
    HiveSelectorState,
    PromptHistory,
    PromptVisit,
    RewardGroupClassification,
    ZeroVarianceType,
    classify_zero_variance,
    restore_selector_rng,
)

__all__ = [
    "ActorEntropyCallDiagnostics",
    "CanonicalHivePrompt",
    "ExplorationControllerConfig",
    "ExplorationUpdate",
    "EntropyScoredPrompt",
    "HIVE_STATE_FILENAME",
    "HiveSelectorSnapshot",
    "HivePromptPreprocessor",
    "HivePreRolloutConfig",
    "HivePreRolloutPreparedRound",
    "HivePreRolloutRoundResult",
    "HivePreRolloutStep",
    "HivePreRolloutStepResult",
    "HiveSelectorState",
    "PromptHistory",
    "PromptIdentityError",
    "PromptEntropyBatchResult",
    "PromptEntropyDiagnostics",
    "PromptEntropyEvaluator",
    "PromptEntropyInputBatch",
    "PromptEntropyRecord",
    "PromptVisit",
    "RewardGroupClassification",
    "RewardHistorySignal",
    "Stage1BatchResult",
    "Stage1Config",
    "Stage1Diagnostics",
    "Stage1PromptDecision",
    "Stage1StepSelector",
    "Stage2BatchResult",
    "Stage2Config",
    "Stage2Diagnostics",
    "Stage2PromptRecord",
    "Stage2Selector",
    "ZeroVarianceType",
    "apply_exploration_update",
    "attach_stable_prompt_ids",
    "classify_zero_variance",
    "compute_exploration_update",
    "compute_prompt_entropy_rpc",
    "compute_reward_history_signal",
    "compute_stage2_counts",
    "extract_stable_prompt_ids",
    "full_categorical_entropy",
    "restore_selector_rng",
    "validate_hive_prompt_preprocessing_scope",
]
